### ISSUE TITLE
Failure at parsing expression with /* comments inside */

### ISSUE THREAD

**Issue by minht11** [asyncLiz/parse-literals#13]
Minifier fails to parse if comment is found next to expression inside template literal: 
``Parse Error: <div .icon=@TEMPLATE_EXPRESSION();* Some comment */}></div>``

Code example that causes the problem:
```javascript
html`<div .icon=${0/* Some comment */}></div>
```
Reproduction
[https://repl.it/repls/ImmaterialPointedInternet](https://repl.it/repls/ImmaterialPointedInternet)

This makes using Typescript const enums and minification impossible.

**Comment by asyncLiz** [comment]
Fixed on main branch
